[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mycalculatordapp = "FBDSxt12GN8x67xDUyx6p9TALc2Cy6T7yxz5W3qcRBti"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/thaind/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
